version: '3.7'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - db_test
    container_name: web_api

  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
    restart: always
    volumes:
      - ./db/:/var/lib/postgres/data
    ports:
      - "5432:5432"
    container_name: db

  db_test:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER_TEST
      POSTGRES_DB: $POSTGRES_DB_TEST
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD_TEST
      POSTGRES_HOST: $POSTGRES_HOST_TEST
    restart: always
    ports:
      - "5431:5432"
    container_name: db_test