"""equipment add field date

Revision ID: 05ba155c88e1
Revises: 450bca07b1b3
Create Date: 2025-05-07 16:30:28.150459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ba155c88e1'
down_revision: Union[str, None] = '450bca07b1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance', 'date')
    # ### end Alembic commands ###
