"""update equipment

Revision ID: 2d56208d806a
Revises: 3068b9106f71
Create Date: 2025-05-07 13:11:20.534471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d56208d806a'
down_revision: Union[str, None] = '3068b9106f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('shift_pk', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shift_pk'], ['shift.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('association_table_maintenance',
    sa.Column('maintenance_pk', sa.Integer(), nullable=True),
    sa.Column('equipment_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_pk'], ['equipment.pk'], ),
    sa.ForeignKeyConstraint(['maintenance_pk'], ['maintenance.pk'], )
    )
    op.drop_constraint('shift_shift_id_key', 'shift', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('shift_shift_id_key', 'shift', ['shift_id'])
    op.drop_table('association_table_maintenance')
    op.drop_table('maintenance')
    # ### end Alembic commands ###
