"""create table map

Revision ID: 2d6c719f42fb
Revises: 05ba155c88e1
Create Date: 2025-05-07 18:33:52.545605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6c719f42fb'
down_revision: Union[str, None] = '05ba155c88e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('production_time_minutes', sa.Integer(), nullable=False),
    sa.Column('setup_time_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('technical_requirements', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('material',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('quantity_per_unit', sa.DECIMAL(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('association_table_equipment',
    sa.Column('equipment_pk', sa.Integer(), nullable=True),
    sa.Column('map_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_pk'], ['equipment.pk'], ),
    sa.ForeignKeyConstraint(['map_pk'], ['map.pk'], )
    )
    op.create_table('association_table_material',
    sa.Column('material_pk', sa.Integer(), nullable=True),
    sa.Column('map_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_pk'], ['map.pk'], ),
    sa.ForeignKeyConstraint(['material_pk'], ['material.pk'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table_material')
    op.drop_table('association_table_equipment')
    op.drop_table('material')
    op.drop_table('map')
    # ### end Alembic commands ###
