"""equipment

Revision ID: 3068b9106f71
Revises: 
Create Date: 2025-05-07 07:52:00.237712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3068b9106f71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('max_parts_per_shift', sa.Integer(), nullable=False),
    sa.Column('efficiency_factor', sa.DECIMAL(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('equipment_id')
    )
    op.create_table('shift',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('shift_id')
    )
    op.create_table('association_table',
    sa.Column('shift_pk', sa.Integer(), nullable=True),
    sa.Column('equipment_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_pk'], ['equipment.pk'], ),
    sa.ForeignKeyConstraint(['shift_pk'], ['shift.pk'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    op.drop_table('shift')
    op.drop_table('equipment')
    # ### end Alembic commands ###
