"""equipment add field duration_hours

Revision ID: 450bca07b1b3
Revises: 2d56208d806a
Create Date: 2025-05-07 16:27:40.628728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450bca07b1b3'
down_revision: Union[str, None] = '2d56208d806a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance', sa.Column('duration_hours', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance', 'duration_hours')
    # ### end Alembic commands ###
