"""add part_id

Revision ID: d12888eed4b8
Revises: 2d6c719f42fb
Create Date: 2025-05-07 18:58:42.647377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12888eed4b8'
down_revision: Union[str, None] = '2d6c719f42fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map', sa.Column('part_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map', 'part_id')
    # ### end Alembic commands ###
