"""create order

Revision ID: e8e78bb66aee
Revises: 80b471358ae1
Create Date: 2025-05-08 13:56:05.273976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e78bb66aee'
down_revision: Union[str, None] = '80b471358ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('part',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('association_table_order',
    sa.Column('part_pk', sa.Integer(), nullable=True),
    sa.Column('order_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_pk'], ['order.pk'], ),
    sa.ForeignKeyConstraint(['part_pk'], ['part.pk'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table_order')
    op.drop_table('part')
    op.drop_table('order')
    # ### end Alembic commands ###
